
GROQ_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwic3ViamVjdCI6ImFwaS1rZXk6NzZkY2E0MDktMDMzOS00OWQxLTg1ZTgtNDU0MDVkNTY5YjVkIn0.lNLWymShNsnVS5r-FXVOdygydF-H6p6g9DoqAOqnGY0"
GEMINI_API_KEY = "AIzaSyCk_RcmZCU5r-uPuuYo8VLNlhxZHZ5Ke9k"
